CREATE TABLE USER (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	username varchar(255) not null,
	password varchar(255) not null
);

CREATE TABLE BEACON (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	uuid varchar(255) not null,
	type varchar(255) not null,
	reference_id varchar(255) not null,
	location_id BIGINT not null,
);

CREATE TABLE BEACON_LOCATION (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	street varchar(255) null,
	house_number varchar(255) null,
	zip_code varchar(255) not null,
	city varchar(255) not null,
	country varchar(255) not null,
	lat DOUBLE null,
	lng DOUBLE null
);

CREATE TABLE Campaign (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	customer varchar(255) not null,
	campaign_name varchar(255) null,
	start_date DATE not null,
	end_date DATE not null,
	beacon_id BIGINT null
);